# Generated by Django 5.1.5 on 2025-02-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('race', models.CharField(choices=[('elfo', 'Elfo'), ('humana', 'Humana'), ('Enano', 'Enano'), ('Hobbit', 'Hobbit')], max_length=50)),
                ('faction', models.CharField(max_length=100)),
                ('ubication', models.CharField(max_length=100)),
                ('arma_equipada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arma_equipada', to='equipment.weapon')),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipamiento', to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amigo', 'Amigo'), ('enemigo', 'Enemigo'), ('neutral', 'Neutral')], max_length=50)),
                ('confidence_level', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaje1', to='character.character')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaje2', to='character.character')),
            ],
        ),
    ]
