# Generated by Django 5.1.6 on 2025-02-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('equipment', '0003_remove_equipment_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='arma_equipada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arma_equipada', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(related_name='equipamiento', to='equipment.equipment'),
        ),
    ]
