# Generated by Django 5.1.6 on 2025-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_character_arma_equipada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
